import Head from 'next/head'
import Image from 'next/image'
import LoginForm from '../components/LoginForm'
import styles from '../styles/Login.module.css'

export default function Login() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main + ' ' + styles.loginPage}> 
      
      <LoginForm />
      </main>
       
    </div>
  )
}
