import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react';
import axios from "axios";
import Cookies from 'js-cookie';

export default function Home() {
  
  const [emailInput, setEmailInput] = useState("");
  const [passwordInput, setPasswordInput] = useState("");
  
  const emailChangeHandler = (e) => {
    setEmailInput(e.target.value);
  };
  const passwordChangeHandler = (e) => {
    setPasswordInput(e.target.value);
  };

  const getProducts = () =>{
  const token = Cookies.get('token');
  
  axios
  .get("https://127.0.0.1:8000/api/get/products", {
     headers:{
     Authorization: 'Bearer $(token)',
    },
  })  

  .then((res) =>{
   console.log('res:', res)
  })
  .catch ((err) => {
    console.log(err)
  });
 }


 const loginClckHandler = () => {
  console.log("should login now");
  const data = {
    email: emailInput,
    password: passwordInput,
  }; 
   console.log("data: ", data);
   
   axios
   .post("https://reqres.in/api/register", data)
   .then((res) => {
    console.log('Promise resolved', res.data);
   const response = res.data;
   
   if (response) {
    const token = response.token;
    console.log('token: ', token);
     
    Cookies.set('token', token);

   }
  }) 
  
  .catch((err) => {
    console.log('There is an error, Something went wrong', err);
   });

  }; 
  

  useEffect (() => {
   getProducts();
  }, [])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        
        <form>
          <label>Email Address</label>
          <br />
          <input
           value={emailInput}
           onChange={emailChangeHandler}
           />
           <hr />
           <label>Password</label>
           <br />
           <input
           value={passwordInput}
           onChange={passwordChangeHandler}
           />
           <hr />
           <button type={"button"} onClick={loginClckHandler}>
            Login Now

           </button>
           <hr />
        </form>
        
        
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
